### ISSUE TITLE
Verge Qt for Mac OS X 10.10 and 10.11

### ISSUE THREAD

**Issue by Mathematixx** [vergecurrency/VERGE#228]
Will there be a wallet for those who have Apple computers with OS X 10.10 and or 10.11? Right now what one gets is a "You can't use this version of the application "Verge-Qt" with this version of OS X" 
It is only made to use OS 10.12 or later :(
Currently, the only option for some users who may not be able to upgrade to newer OS X  is having to buy new computers.

**Comment by mithunan** [comment]
I have Mac 10.12.6 and i got the same message. I ran the terminal commands that was tweeted and it worked. 

https://twitter.com/vergecurrency/status/947790293163749377

**Comment by Mathematixx** [comment]
You have Sierra. 
I am asking for those with previous versions 10.10 and 10.11 (Yosemite and El Capitan)

**Comment by ekryski** [comment]
@Mathematixx I'll see if we can do this. We can try adding another build to our Travis pipeline but I'd like to get OS X 10.12 building so it's an easy install first. There are a lot of dependencies that seem to be version specific so we'll have to see if they will compile on an older version of OS X and XCode.

A long way to say, not right away but we'll see what we can do. The idea is for everyone to be able to use the wallet wherever they are.

**Comment by robbybroon** [comment]
Hi Guys,

I had the same problem - am running OS X El Capitan (10.11.6) on Early 2009 Mac Mini, and can't upgrade. I tried Verge-QT and it won't start up, says it is compiled for 10.12+, tried Electrum-XVG (2.4, latest mac binary available - 2.4.1 only available on Windows and Linux) and it crashes on startup on El Capitan and on a friend's Sierra install; so - I followed these instructions:
https://github.com/vergecurrency/VERGE

And it worked great! I have Verge-QT running on Mac OS 10.11 El Capitan on my Early 2009 Mac Mini - the 4.0 Wraith release, built from source - I can see my balance and am currently syncing with the network.
![verge_osx_10 11](https://user-images.githubusercontent.com/35031440/34485252-90b00af6-efc1-11e7-9630-89d34b13b698.png)

**Comment by Mathematixx** [comment]
@ekryski Yes, I totally understand. I will keep my verges in the exchange for now.

**Comment by mik3ondop3** [comment]
my loading bar doesn't move

**Comment by robbybroon** [comment]
it takes a long time to initially load - I bootstrapped by downaloading the whole blockchain as a zip file to start, then it took about 20 mins to initially get off the loading screen before the window appeared.

**Comment by ksteigerwald** [comment]
Mine did that for some time to, that is the network catching up the head of the blockchain. My guess is you downloaded it from the 30th, so it has a few extra days to catch up on. It works very well on Mac once you get it going.

**Comment by robbybroon** [comment]
you can download the blockchain and dump it into ~/Library/Application Support/VERGE

**Comment by mik3ondop3** [comment]
where i can download the blockchain?

**Comment by robbybroon** [comment]
here:
https://verge-blockchain.com/

**Comment by mik3ondop3** [comment]
thanks

**Comment by mik3ondop3** [comment]
ok i downloaded and extracted the blockchain data in the VERGE folder so now i have to re-open the application and wait to sync?

**Comment by robbybroon** [comment]
yes - you should really make sure the application is shut down while you copy the files in - so no locks are open in the OS.

**Comment by clarkw** [comment]
Running OSX 10.10.5 (Yosemite), I was able to successfully build and run using the instructions at [https://github.com/vergecurrency/VERGE](https://github.com/vergecurrency/VERGE)

I am currently syncing with the network.

My machine was already set up for development. Not sure if that helped.

![verge_screen_cap](https://user-images.githubusercontent.com/647285/34495008-362fe812-efc1-11e7-82e7-57679ca4c91f.png)

**Comment by robbybroon** [comment]
I still think you/we need a working Verge client for pre-Sierra Macs that can be downloaded as a binary - building it ourselves is not a great solution as it needs all the dev tools installed and is quite techie in nature. To gain mainstream adoption, Verge needs a download and go wallet solution.

The official Verge homepage directs users to download Electrum-XVG rather than Verge-QT, for some reason, and this Electrum version is broken on all versions of MacOS - it doesn't even start up. Why don't they push Verge-QT instead, as the official wallet? It at least works on Sierra...

I'm also curious about the binary filesize - the download from git of the sierra only version is around 160-180 meg, my compiled binary is 8.7 meg - that's a very large size differential - any ideas why?

My sync just completed, btw:
![sync complete](https://user-images.githubusercontent.com/35031440/34495449-29817136-efed-11e7-9611-15d49af2629c.png)

**Comment by rickbakker** [comment]
I just tried to get it going on MacOS El Capitan but i got this as a result:

bitcoinrpc.cpp:682:49: error: too many template arguments for class template 'basic_socket_acceptor'
static void RPCAcceptHandler(boost::shared_ptr< basic_socket_acceptor<Protocol, SocketAcceptorService> > acceptor,
                                                ^                               ~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is declared here
class basic_socket_acceptor
      ^
bitcoinrpc.cpp:692:42: error: too many template arguments for class template 'basic_socket_acceptor'
static void RPCListen(boost::shared_ptr< basic_socket_acceptor<Protocol, SocketAcceptorService> > acceptor,
                                         ^                               ~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is declared here
class basic_socket_acceptor
      ^
bitcoinrpc.cpp:714:49: error: too many template arguments for class template 'basic_socket_acceptor'
static void RPCAcceptHandler(boost::shared_ptr< basic_socket_acceptor<Protocol, SocketAcceptorService> > acceptor,
                                                ^                               ~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is declared here
class basic_socket_acceptor
      ^
bitcoinrpc.cpp:789:18: error: no matching constructor for initialization of 'ssl::context'
    ssl::context context(io_service, ssl::context::sslv23);
                 ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/ssl/impl/context.ipp:63:10: note: candidate constructor not viable: requires single argument 'm', but 2
      arguments were provided
context::context(context::method m)
         ^
/usr/local/include/boost/asio/ssl/context.hpp:36:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1
      argument, but 2 were provided
class context
      ^
bitcoinrpc.cpp:1099:18: error: no matching constructor for initialization of 'ssl::context'
    ssl::context context(io_service, ssl::context::sslv23);
                 ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/ssl/impl/context.ipp:63:10: note: candidate constructor not viable: requires single argument 'm', but 2
      arguments were provided
context::context(context::method m)
         ^
/usr/local/include/boost/asio/ssl/context.hpp:36:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1
      argument, but 2 were provided
class context
      ^
1 warning and 5 errors generated.
make[1]: *** [libbitcoin_server_a-bitcoinrpc.o] Error 1
make: *** [all-recursive] Error 1

When running: ./building/mac/build.sh

**Comment by clarkw** [comment]
I'd look close at your boost install.

**Comment by rickbakker** [comment]
Yeah seems like something from boost isnt doing it's job. Gonna look into this tomorrow again. Saw some more people with the same issues. Will report back when i have a fix for this.

**Comment by gutterstyle** [comment]
is it normal that when i run this wallet on my macbook pro my computer gets extremely hot? as soon as i close it it cools off fast but you can fry an egg on it when ever i open the wallet.

**Comment by DanielinChina2016** [comment]
Are you mining?





On 2018-01-02 14:50 , gutterstyle<mailto:notifications@github.com> Wrote:


is it normal that when i run this wallet on my macbook pro my computer gets extremely hot? as soon as i close it it cools off fast but you can fry an egg on it when ever i open the wallet.

**Comment by clarkw** [comment]
How does one mine using the wallet?

**Comment by gutterstyle** [comment]
No I’m not mining. Does no one else have this issue? It’s just running the wallet. It makes my computer get rediculisly hot and fans get super noise. As soon as I close the wallet it cools off and and fans slow down. I have a brand new (4 days old) MacBook Pro

**Comment by CameronAdair** [comment]
Im on 10.11.6
homebrew install said i had some conflicting files in /usr/local/lib and /usr/local/include
deleted them and started over
app still crossed out and gives "You have OS X 10.11.6. The application requires OS X 10.12 or later." dialogue

**Comment by Mahadmoh** [comment]
Guys. My knowledge on programming is vert limited . Perhaps you can help. My main issue is I am running MacOSX 10.9.5 Maverick. I want install Verge wallet for (Mac). I am getting error messages on both attempts to install: Verge MacOSX wallet & Verge OSX Electrum wallet wizards wont run .
 
**Verge Mac OSX:**
Error message( this is only part of the error message)
Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Volumes/VERGE-Qt/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found
 
**Verge OSX Electrum ** 

Error Message ( this is only part of the error message)

rashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000

Dyld Error Message:
  Symbol not found: _getentropy
  Referenced from: /Volumes/VOLUME/Electrum-XVG.app/Contents/Frameworks/Python.framework/Versions/2.7/Python
  Expected in: /usr/lib/libSystem.B.dylib

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
then there is endless thread of 

any help would be much appreciated thanks 

Mah

**Comment by shawnyuan** [comment]
I can't use the Mac or the Electrum wallet. Can we get this fixed? Please don't abandon those that are using 10.10 and 10.11.

**Comment by justinvforvendetta** [comment]
fixed verge qt in latest commit

**Comment by shawnyuan** [comment]
justinvforvendetta@ Still not working in verge qt. Have you verified in Mac 10.10?  

Thanks
