### ISSUE TITLE
TX with stealth address hang

### ISSUE THREAD

**Issue by Hamdiovish** [vergecurrency/VERGE#336]
Hello dear community,

I'm about to test the stealth address feature, i've sent 0.5 XVG to a stealth address but it didn't got confirmed nor received the 0.5 XVG and it was blocked on "Status: 0/unconfirmed, broadcast through 7 node(s)"

I want to mention that:
- The stealth address is on the same wallet.
- The walled is synchronized
- The same wallet received an ammount of XVG on the ordinary address and the confirmations done within few munites.

Spec:
- Operation system: Ubuntu 16.04 LTS

Test case:
TX: 3f6df6539557e833611b73f215205ac93d3f5c465c2305d61f6a805a102b09e5
Stealth Address: smYizfYRQUitnfMwe7ECC47bGRwn3QUTZukgAHzPdmJykUV7rASgzEfUmawRV1FMjZB1BXRDVtPa3FYTooXoSoCQBqswsQ7SsTdJVd

**Note: I aimed to contribute to the Verge project and join the amazing team behind it, so i forked the project and i started testing things, no FUD intended.
I've some question to start working on the project:
- Any way to start the QT Wallet in debug mode so we can see log.
- Are there any Faucet or Test Net so we can test transaction freely without the feer of loosing real money.
- A TX with Stealth address will not appear on the blockchain explorer, is it like that?**

Here is the screenshots:
The issue of the TX with the Stealth Address,
Another note, the Linux version of the QT Wallet have no upper menu to alter the address.
![err screenshot from 2018-01-03 19-54-18](https://user-images.githubusercontent.com/2495140/34536659-2a96c9b6-f0c6-11e7-8cd7-124bd47b63b9.png)

Keep up the good work,
Regards

**Comment by jderwish** [comment]
@Hamdiovish  I have exact same problem, and I did sent the coins from one wallet on ubuntu to another wallet. Wallet sync and still no confirmations.

**Comment by jderwish** [comment]
![image](https://user-images.githubusercontent.com/32366979/34539456-84e5e9ec-f09e-11e7-969b-d2bf2ba3c872.png)

**Comment by paradoxicalNL** [comment]
Can I send a coin to some1's stealth address. I'm also using same client/wallet as sender/receiver, which is weird of course, why would you want to do that (other then testing)

**Comment by jderwish** [comment]
Here you go..
![image](https://user-images.githubusercontent.com/32366979/34539794-0c61d196-f0a0-11e7-88b0-b28398bbeb5c.png)

**Comment by paradoxicalNL** [comment]
uhm, please send me the string that is a lot of chars

**Comment by Hamdiovish** [comment]
@paradoxicalNL tests are blind, all the situations should be treated well and the extreme situations should tested before the ordinary ones.
I wish someone can answer me on the following point so i can start debugging it by myself:

**Any way to start the QT Wallet in debug mode so we can see log.
Are there any Faucet or Test Net so we can test transaction freely without the feer of loosing real money.
A TX with Stealth address will not appear on the blockchain explorer, is it like that?**

By the way, i tested sending to another wallet as well, but the same issue occurs.

**Comment by paradoxicalNL** [comment]
I have sent 0.5 xvg to above address:

Status: 0/offline, has not been successfully broadcast yet
Date: 03-01-18 22:14
Debit: -0.50 XVG
Transaction fee: -0.10 XVG
Net amount: -0.60 XVG
Transaction ID: 71f8c3d8f96edbc80effe321c18b364f7c65103824f9d75de98d7517a517183c

I got served an error that i accidental clicked away, I repeated:
Error: The transaction was rejected. This might happen if some of the coins in your wallet where already spent, such as if you used a copy of wallet.dat and coins where spent in the copy but not maked as spent here,

Actual balance 1.10 (after)
Fully synced.

**Comment by pasrom** [comment]
Do you find 

> ERROR: CTxMemPool::accept() : nonstandard transaction type

in your log file? (Help -> Debug -> Information -> Open).
If yes, i think this issue is also related to #296.

**Comment by Hamdiovish** [comment]
The Linux version has no a top manu.

I confirm the error message too:
"Error: The transaction was rejected. This might happen if some of the coins in your wallet where already spent, such as if you used a copy of wallet.dat and coins where spent in the copy but not maked as spent here"
Although that, the balance reduced

**Comment by pasrom** [comment]
the debug log is at ~/VERGE/debug.log
Did you restart your wallet and the balance is the same as before you close it?

**Comment by jderwish** [comment]
@pasrom  no debug log in my case, do you have to start the wallet in debug mode?

**Comment by Hamdiovish** [comment]
@pasrom yes i confirm, i found "ERROR: CTxMemPool::accept() : nonstandard transaction type" in the log file.

Just to mention, the debug log is at ~/.VERGE/debug.log, the hidden folder.

Here is the part of the log:

[...
CTxMemPool::accept() : accepted 1c343967b3 (poolsz 12)
CTxMemPool::accept() : accepted c796829cb1 (poolsz 13)
Flushed 15777 addresses to peers.dat  63ms
CTxMemPool::accept() : accepted e5773c5ffa (poolsz 14)
CTxMemPool::accept() : accepted 98ff3ece48 (poolsz 15)
CommitTransaction:
CTransaction(hash=3f6df65395, nTime=1515004802, ver=1, vin.size=1, vout.size=2, nLockTime=0)
    CTxIn(COutPoint(17c9642098, 7), scriptSig=304502204bf548219fe1e9f0)
    CTxOut(nValue=0.30, scriptPubKey=OP_DUP OP_HASH160 bd7498ba7541fb6d1f98187167868884dafbe080 OP_EQUALVERIFY OP_CHECKSIG)
    CTxOut(error)
AddToWallet 3f6df65395  new
WalletUpdateSpent found spent coin 0.90 XVG 17c964209872e9756f48d7f44e040416c6ed35d12d78e2bb44dc0b7265e19012
NotifyTransactionChanged 17c964209872e9756f48d7f44e040416c6ed35d12d78e2bb44dc0b7265e19012 status=1
NotifyTransactionChanged 3f6df6539557e833611b73f215205ac93d3f5c465c2305d61f6a805a102b09e5 status=0
NotifyTransactionChanged 17c964209872e9756f48d7f44e040416c6ed35d12d78e2bb44dc0b7265e19012 status=1
ERROR: CTxMemPool::accept() : nonstandard transaction type
CommitTransaction() : Error: Transaction not validupdateWallet 17c964209872e9756f48d7f44e040416c6ed35d12d78e2bb44dc0b7265e19012 1
keypool added key 104, size=101
   inWallet=1 inModel=1 Index=0-1 showTransaction=1 derivedStatus=1
updateWallet 3f6df6539557e833611b73f215205ac93d3f5c465c2305d61f6a805a102b09e5 0
   inWallet=1 inModel=0 Index=1-1 showTransaction=1 derivedStatus=0
updateWallet 17c964209872e9756f48d7f44e040416c6ed35d12d78e2bb44dc0b7265e19012 1
   inWallet=1 inModel=1 Index=0-1 showTransaction=1 derivedStatus=1
CTxMemPool::accept() : accepted f2deff98d8 (poolsz 16)
Flushing wallet.dat
Flushed wallet.dat 55ms
...]

**Comment by paradoxicalNL** [comment]
@jderwish did you receive the funds?

**Comment by jderwish** [comment]
@paradoxicalNL Nope and Wallet is sync.

**Comment by paradoxicalNL** [comment]
Not sure if this expected, wallet addresses come up empty as well:

![address](https://user-images.githubusercontent.com/24474572/34542082-4d2858f4-f0db-11e7-8645-ab69e6c71a98.jpg)

**Comment by jderwish** [comment]
Here is sending another transaction - 
![image](https://user-images.githubusercontent.com/32366979/34544004-d733852a-f0b1-11e7-9d57-112a82d766e1.png)


Debug Log tail


jderwish@instance-1:~/.VERGE$ tail debug.log
getblocks 1391699 to dd53e324a8ba11f57fa1 limit 500
  getblocks stopping at limit 1392198 00000000000db3eb4178
received getdata for: tx b6ccbfd05b4757633d48
CTxMemPool::accept() : accepted bf36ccb69a (poolsz 5)
CTxMemPool::accept() : accepted c43e2971a6 (poolsz 6)
CTxMemPool::accept() : accepted 373af89d3b (poolsz 7)
received getdata for: tx 373af89d3b49d461a6e9
received getdata for: tx 373af89d3b49d461a6e9
CTxMemPool::accept() : accepted bdea876378 (poolsz 8)
received getdata (34 invsz)
jderwish@instance-1:~/.VERGE$ tail -f debug.log
CTxMemPool::accept() : accepted bf36ccb69a (poolsz 5)
CTxMemPool::accept() : accepted c43e2971a6 (poolsz 6)
CTxMemPool::accept() : accepted 373af89d3b (poolsz 7)
received getdata for: tx 373af89d3b49d461a6e9
received getdata for: tx 373af89d3b49d461a6e9
CTxMemPool::accept() : accepted bdea876378 (poolsz 8)
received getdata (34 invsz)
CTxMemPool::accept() : accepted 169e89c85a (poolsz 9)
getblocks 1335400 to a6393cc48b4a47886d6f limit 500
  getblocks stopping at limit 1335899 d06e2adffd5bd9d50412
Flushed 11103 addresses to peers.dat  18ms
received block 4b3d595d1d7de3e8af0a
AddToWallet 2752beb486  update
NotifyTransactionChanged 2752beb48624315a25c8c63a00dfe73d5ce6642713b5a2e2a8e641d2c07e7c01 status=1
updateWallet 2752beb48624315a25c8c63a00dfe73d5ce6642713b5a2e2a8e641d2c07e7c01 1
   inWallet=1 inModel=1 Index=0-1 showTransaction=1 derivedStatus=1
SetBestChain: new best=4b3d595d1d7de3e8af0a  height=1772615  trust=1772616  date=01/03/2018 23:10:11
ProcessBlock: ACCEPTED (groestl)
getblocks -1 to 00000000000000000000 limit 500
Flushing wallet.dat
Flushed wallet.dat 3ms
getblocks -1 to 00000000000000000000 limit 500
received getdata (2 invsz)
CTxMemPool::accept() : accepted a6bc8bd3f7 (poolsz 6)
CTxMemPool::accept() : accepted e1a78f2d4c (poolsz 7)
CWalletTx::GetAmounts: Unknown transaction type found, txid e758e33ec6baec745712a5f06b4eaeb571da4eaf7cd5f4b1042be45ee9589871
CTxMemPool::accept() : accepted 39a8a840c4 (poolsz 8)
CTxMemPool::accept() : accepted 1a72dfdc07 (poolsz 9)
CTxMemPool::accept() : accepted fb70f42ae6 (poolsz 10)
CTxMemPool::accept() : accepted 6d54eee2cd (poolsz 11)
received getdata for: tx 6d54eee2cd979dc73e33
CTxMemPool::accept() : accepted 5a8426d0bd (poolsz 12)
CTxMemPool::accept() : accepted 26cf78cfb2 (poolsz 13)
CTxMemPool::accept() : accepted a6cd4d0988 (poolsz 14)
CTxMemPool::accept() : accepted 9e5809f4b8 (poolsz 15)
CTxMemPool::accept() : accepted ae0c4f2fd5 (poolsz 16)
CTxMemPool::accept() : accepted d8aadf8d62 (poolsz 17)
CTxMemPool::accept() : accepted 8fdd2deddf (poolsz 18)
received block 14033cfb62ec8eb57ef4
SetBestChain: new best=14033cfb62ec8eb57ef4  height=1772616  trust=1772617  date=01/03/2018 23:10:46
ProcessBlock: ACCEPTED (groestl)
getblocks -1 to 00000000000000000000 limit 500
received getdata (34 invsz)
Flushing wallet.dat
Flushed wallet.dat 3ms
getblocks 1335900 to a6393cc48b4a47886d6f limit 500
  getblocks stopping at limit 1336399 000000000030167e55fc
received getdata (5 invsz)
CTxMemPool::accept() : accepted dfb31c036b (poolsz 14)
CTxMemPool::accept() : accepted 1d7880ddbf (poolsz 15)
received getdata (2 invsz)
CTxMemPool::accept() : accepted c55a1c1ed1 (poolsz 16)
CommitTransaction:
CTransaction(hash=07dff3e3e5, nTime=1515021136, ver=1, vin.size=1, vout.size=1, nLockTime=0)
    CTxIn(COutPoint(2752beb486, 1), scriptSig=3046022100f79453809aaedd)
    CTxOut(error)
AddToWallet 07dff3e3e5  new
WalletUpdateSpent found spent coin 1.00 XVG 2752beb48624315a25c8c63a00dfe73d5ce6642713b5a2e2a8e641d2c07e7c01
NotifyTransactionChanged 2752beb48624315a25c8c63a00dfe73d5ce6642713b5a2e2a8e641d2c07e7c01 status=1
NotifyTransactionChanged 07dff3e3e528773afde250aeddbc9eb5256d71cf0d0893d44f4355780febc010 status=0
NotifyTransactionChanged 2752beb48624315a25c8c63a00dfe73d5ce6642713b5a2e2a8e641d2c07e7c01 status=1
ERROR: CTxMemPool::accept() : nonstandard transaction type
CommitTransaction() : Error: Transaction not validupdateWallet 2752beb48624315a25c8c63a00dfe73d5ce6642713b5a2e2a8e641d2c07e7c01 1
   inWallet=1 inModel=1 Index=0-1 showTransaction=1 derivedStatus=1
updateWallet 07dff3e3e528773afde250aeddbc9eb5256d71cf0d0893d44f4355780febc010 0
   inWallet=1 inModel=0 Index=0-0 showTransaction=1 derivedStatus=0
updateWallet 2752beb48624315a25c8c63a00dfe73d5ce6642713b5a2e2a8e641d2c07e7c01 1
   inWallet=1 inModel=1 Index=1-2 showTransaction=1 derivedStatus=1
Flushed 11103 addresses to peers.dat  16ms
Flushing wallet.dat
Flushed wallet.dat 2ms
received block adbd44c63a9856a6ee73
SetBestChain: new best=adbd44c63a9856a6ee73  height=1772617  trust=1772618  date=01/03/2018 23:11:33
ProcessBlock: ACCEPTED (groestl)
Flushing wallet.dat
Flushed wallet.dat 3ms
received getdata (34 invsz)

**Comment by jderwish** [comment]
Same here

![image](https://user-images.githubusercontent.com/32366979/34544078-28b3ab46-f0b2-11e7-9776-aa4c1b7976fb.png)

**Comment by paradoxicalNL** [comment]
Fix is committed. I'll compile and test once merged.

**Comment by justinvforvendetta** [comment]
guys please also post what commit you are on at the time of sending/receiving/etc.

**Comment by jderwish** [comment]
So we know which commit has this fixed?

**Comment by justinvforvendetta** [comment]
well so that people know what commit you are on when you are making functions, because newer commits could have changes to specific related issues

**Comment by jderwish** [comment]
![image](https://user-images.githubusercontent.com/32366979/34545409-ccd89a3a-f0ba-11e7-8b23-8bd3b7c9047a.png)

**Comment by fradelo** [comment]
There is a restriction in line 661 of main.cpp and stealth transactions are not processed if not in testnet.

**Comment by jderwish** [comment]
@fradelo I saw that and thought it was fixed on the released I compile. If I update source code and recompile it should be fixed? or code is not merged yet ?

**Comment by paradoxicalNL** [comment]
@fradelo same goes for me, also just compiled.
@jderwish your address still the same I presume? Also sending you funds as test

**Comment by fradelo** [comment]
It is not fixed please update source and recompile and let us know the result.

**Comment by paradoxicalNL** [comment]
@fradelo can you supply code so I know 100% it's ok

    // Rather not work on nonstandard transactions (unless -testnet)
    if (!fTestNet && !tx.IsStandard())
        return error("CTxMemPool::accept() : nonstandard transaction type");

**Comment by jderwish** [comment]
@fradelo  you want us to manually update the code and recompile ?

**Comment by fradelo** [comment]
@paradoxicalNL Yeap

**Comment by jderwish** [comment]
@paradoxicalNL just commented and recompiling now.

**Comment by paradoxicalNL** [comment]
Results build: v2.1.0.0-7d417ad-beta
Ubuntu 16.04

sending to own stealth address: transaction rejected
Error: The transaction was rejected. This might happen if some of the coins in your wallet were already spent, such as if you used a copy of wallet.dat and coins were spent in the copy but not marked as spent here.

sending to remote stealth address: transaction rejected
Error: The transaction was rejected. This might happen if some of the coins in your wallet were already spent, such as if you used a copy of wallet.dat and coins were spent in the copy but not marked as spent here.

main.cpp has:

// Rather not work on nonstandard transactions (unless -testnet)
//if (!fTestNet && !tx.IsStandard())
//    return error("CTxMemPool::accept() : nonstandard transaction type");

funds got deducted, some miner happy now? ;)

**Comment by jderwish** [comment]
@paradoxicalNL Syncing now - are you ready to re-test?

**Comment by jderwish** [comment]
@justinvforvendetta can you please join for few minutes ? https://discord.gg/khdbGj

**Comment by justinvforvendetta** [comment]
everyone testing in this thread, should be on commit: https://github.com/vergecurrency/VERGE/commit/75fa3808175261df1e5cdb0d243a166ba63b7532

**Comment by jderwish** [comment]
@justinvforvendetta @paradoxicalNL  recompiling on commit 75fa380 as requested.

**Comment by jderwish** [comment]
@justinvforvendetta is there a better way to pull config changes ? instead of me manually updating the files in ubuntu

**Comment by paradoxicalNL** [comment]
I'm done recompling on commit https://github.com/vergecurrency/VERGE/commit/75fa3808175261df1e5cdb0d243a166ba63b7532 as requested running test after start. 

Gave my vm some extra cores but loading block index is slow, and only single core it seems. If anyone has tips to speed that up, welcome.

**Comment by jderwish** [comment]
@paradoxicalNL I am using GCP 4 vCPU and 8Gig with 20 Gig SSD - super fast :-)

**Comment by justinvforvendetta** [comment]
@jderwish yeah use git pull

**Comment by paradoxicalNL** [comment]
@justinvforvendetta 

updated to latest https://github.com/vergecurrency/VERGE/commit/75fa3808175261df1e5cdb0d243a166ba63b7532 
VERGE: v2.1.0.0-7d417ad-beta

Error: The transaction was rejected. This might happen if some of the coins in your wallet were already spent, such as if you used a copy of wallet.dat and coins were spent in the copy but not marked as spent here.

debug:
CommitTransaction:
CTransaction(hash=c9cf7a6c52, nTime=1515030514, ver=1, vin.size=1, vout.size=2, nLockTime=0)
    CTxIn(COutPoint(2e8153ecb8, 0), scriptSig=3046022100a11b991ac0a34f)
    CTxOut(nValue=0.20, scriptPubKey=OP_DUP OP_HASH160 d45663cbaae2fb151bfb3173e23ad21d672cb115 OP_EQUALVERIFY OP_CHECKSIG)
    CTxOut(error)
AddToWallet c9cf7a6c52  new
WalletUpdateSpent found spent coin 0.50 XVG 2e8153ecb8daf8a508f3e5656590056fd1b7b6e9bcb8e0080369dfdc982f8d30
NotifyTransactionChanged 2e8153ecb8daf8a508f3e5656590056fd1b7b6e9bcb8e0080369dfdc982f8d30 status=1
NotifyTransactionChanged c9cf7a6c52c6cfd553ef05efd6fcbb8c31962c76a972edb894506eb9d608f04d status=0
NotifyTransactionChanged 2e8153ecb8daf8a508f3e5656590056fd1b7b6e9bcb8e0080369dfdc982f8d30 status=1
ERROR: CTxMemPool::accept() : nonstandard transaction type
CommitTransaction() : Error: Transaction not validkeypool added key 108, size=101
updateWallet 2e8153ecb8daf8a508f3e5656590056fd1b7b6e9bcb8e0080369dfdc982f8d30 1
   inWallet=1 inModel=1 Index=1-2 showTransaction=1 derivedStatus=1
updateWallet c9cf7a6c52c6cfd553ef05efd6fcbb8c31962c76a972edb894506eb9d608f04d 0
   inWallet=1 inModel=0 Index=4-4 showTransaction=1 derivedStatus=0
updateWallet 2e8153ecb8daf8a508f3e5656590056fd1b7b6e9bcb8e0080369dfdc982f8d30 1
   inWallet=1 inModel=1 Index=1-2 showTransaction=1 derivedStatus=1
CTxMemPool::accept() : accepted 8a64122b51 (poolsz 3)
getblocks -1 to 00000000000000000000 limit 500
CTxMemPool::accept() : accepted 280957fcba (poolsz 4)
CTxMemPool::accept() : accepted d8cae1f4d4 (poolsz 5)
CTxMemPool::accept() : accepted 98618240b4 (poolsz 6)
Flushing wallet.dat

**Comment by jderwish** [comment]
@paradoxicalNL Now I understand, how to compile new latest release - you need to go to VERGE folder and type git pull, once the changes are downloaded, recompile using sudo sh go.sh :-)

No need to change manually, since we don't have access to commit to the code.

**Comment by fradelo** [comment]
@paradoxicalNL did you comment out the code again because i see the same error message ERROR: CTxMemPool::accept() : nonstandard transaction type

**Comment by justinvforvendetta** [comment]
i prefer to go to ~/verge and do this: 
make clean && git pull && ./autogen.sh && ./configure && make

**Comment by paradoxicalNL** [comment]
@fradelo 

should be line 718 instead, not the diff.
recompiling now.

        // Check for non-standard pay-to-script-hash in inputs
        if (!tx.AreInputsStandard(mapInputs) && !fTestNet)
            return error("CTxMemPool::accept() : nonstandard transaction input");

**Comment by fradelo** [comment]
@paradoxicalNL 
Next Error also comes from line 2393
 // Broadcast
        if (!wtxNew.AcceptToMemoryPool())
        {
            // This must not fail. The transaction has already been signed and recorded.
            printf("CommitTransaction() : Error: Transaction not valid");
            return false;
        }

**Comment by fradelo** [comment]
@paradoxicalNL get source again see #343 already merged

**Comment by paradoxicalNL** [comment]
@fradelo on last attempt I used a decreased fee, so that must have been the reason?

!tx.IsStandard()) = !0.1 right?

**Comment by justinvforvendetta** [comment]
another update. everyone testing should be on https://github.com/vergecurrency/VERGE/commit/05ca00b3574e66a253c2153ffface4cb75bd2e26

**Comment by paradoxicalNL** [comment]
When i send a transaction smaller then 1 (i tried 0.1) I get 'Error transaction creation failed'.
Uncommenting  did not help:

    // Check for non-standard pay-to-script-hash in inputs
    //if (!tx.AreInputsStandard(mapInputs) && !fTestNet)
    //   return error("CTxMemPool::accept() : nonstandard transaction input");

**Comment by justinvforvendetta** [comment]
@paradoxicalNL are you on 05ca00b?

**Comment by jderwish** [comment]
@justinvforvendetta @paradoxicalNL just did pull and recompiling latest pull...05ca00b?

**Comment by paradoxicalNL** [comment]
I recompiled from https://github.com/vergecurrency/VERGE/commit/05ca00b3574e66a253c2153ffface4cb75bd2e26

Error: The transaction was rejected. This might happen if some of the coins in your wallet were already spent, such as if you used a copy of wallet.dat and coins were spent in the copy but not marked as spent here.

**Comment by jderwish** [comment]
@justinvforvendetta  the transactions to stealthaddresses that failed or not confirmed - what is going to happen to the actual coins?

**Comment by techpoy** [comment]
Guys can somebody build and load the compiled binaries for windows? I would like to test the build as well but I never worked on other platforms much and I couldn't build on linux tools for windows. I would like to make sure the UI bugs are taken care of. Thanks in advance

**Comment by Positivism** [comment]
@justinvforvendetta Can confirm still happens in 05ca00b.

**Comment by justinvforvendetta** [comment]
i think we have the fix, next commit

**Comment by Positivism** [comment]
Well test on sierra.

**Comment by Positivism** [comment]
Will test on sierra.

**Comment by paradoxicalNL** [comment]
@justinvforvendetta @michpiatek @fradelo 
https://github.com/vergecurrency/VERGE/commit/05ca00b3574e66a253c2153ffface4cb75bd2e26
fixed stealth tx #350

Still fails here:

CommitTransaction:
CTransaction(hash=9bde7bf840, nTime=1515048755, ver=1, vin.size=1, vout.size=2, nLockTime=0)
    CTxIn(COutPoint(1ef2c8fb11, 0), scriptSig=3044022017664adf6a6b56d1)
    CTxOut(nValue=1.18, scriptPubKey=OP_DUP OP_HASH160 cf07d2ab12b807eabc556f8a0e06e565c3193802 OP_EQUALVERIFY OP_CHECKSIG)
    CTxOut(error)
AddToWallet 9bde7bf840  new
WalletUpdateSpent found spent coin 1.39 XVG 1ef2c8fb11822737af9bf160eba8110ce604c331e9afb5219edd1868421bddd0
NotifyTransactionChanged 1ef2c8fb11822737af9bf160eba8110ce604c331e9afb5219edd1868421bddd0 status=1
NotifyTransactionChanged 9bde7bf840024506ad98c968f07e87659e265a2f8ea24124858d2b5ffe1766ec status=0
NotifyTransactionChanged 1ef2c8fb11822737af9bf160eba8110ce604c331e9afb5219edd1868421bddd0 status=1
ERROR: CTxMemPool::accept() : nonstandard transaction type
CommitTransaction() : Error: Transaction not validreceived block 60b3cd441bd4328136b5
updateWallet 1ef2c8fb11822737af9bf160eba8110ce604c331e9afb5219edd1868421bddd0 1
   inWallet=1 inModel=1 Index=2-3 showTransaction=1 derivedStatus=1
updateWallet 9bde7bf840024506ad98c968f07e87659e265a2f8ea24124858d2b5ffe1766ec 0
   inWallet=1 inModel=0 Index=7-7 showTransaction=1 derivedStatus=0
updateWallet 1ef2c8fb11822737af9bf160eba8110ce604c331e9afb5219edd1868421bddd0 1
   inWallet=1 inModel=1 Index=2-3 showTransaction=1 derivedStatus=1

**Comment by swat69** [comment]
commit https://github.com/vergecurrency/VERGE/commit/612baf704c7ffecc37914f10ad10b5b1e843137b

coins are not being received.

CommitTransaction:
CTransaction(hash=42bbeeb668, nTime=1515051543, ver=1, vin.size=1, vout.size=3, nLockTime=0)
    CTxIn(COutPoint(3a81f7200e, 0), scriptSig=3045022002f27372edde2928)
    CTxOut(nValue=7.20, scriptPubKey=OP_DUP OP_HASH160 c2941ac2d9071a7ec1ac04aa126b16df1d49e558 OP_EQUALVERIFY OP_CHECKSIG)
    CTxOut(nValue=2.00, scriptPubKey=OP_DUP OP_HASH160 f9ec0392cff66f411ba9cec31ed0df3d990615e3 OP_EQUALVERIFY OP_CHECKSIG)
    CTxOut(nValue=0.00, scriptPubKey=OP_RETURN 020251c8411ea0b0bf280305824014bb769bc10cf70d2cf09adc2b95168613d35d)
AddToWallet 42bbeeb668  new
WalletUpdateSpent found spent coin 9.30 XVG 3a81f7200e653e807400ac20ee3e35de4316ceb396c8c988e607a6a62112cfe6
NotifyTransactionChanged 3a81f7200e653e807400ac20ee3e35de4316ceb396c8c988e607a6a62112cfe6 status=1
NotifyTransactionChanged 42bbeeb668c148f42d85a5237d2e20c704aeaaefca28f20a61eb13c39e3ec9bb status=0
NotifyTransactionChanged 3a81f7200e653e807400ac20ee3e35de4316ceb396c8c988e607a6a62112cfe6 status=1
CTxMemPool::accept() : accepted 42bbeeb668 (poolsz 4)
Relaying wtx 42bbeeb668
Added time data, samples 5, offset -2 (+0 minutes)
nTimeOffset = -1  (+0 minutes)
receive version message: version 90001, blocks=1773487, us=93.181.29.179:44656, them=185.154.15.191:21102, peer=185.154.15.191:21102
updateWallet 3a81f7200e653e807400ac20ee3e35de4316ceb396c8c988e607a6a62112cfe6 1
   inWallet=1 inModel=1 Index=5-7 showTransaction=1 derivedStatus=1
updateWallet 42bbeeb668c148f42d85a5237d2e20c704aeaaefca28f20a61eb13c39e3ec9bb 0
   inWallet=1 inModel=0 Index=7-7 showTransaction=1 derivedStatus=0
updateWallet 3a81f7200e653e807400ac20ee3e35de4316ceb396c8c988e607a6a62112cfe6 1
   inWallet=1 inModel=1 Index=5-7 showTransaction=1 derivedStatus=1
CTxMemPool::accept() : accepted f81c4962bf (poolsz 5)

![cap2](https://user-images.githubusercontent.com/28594828/34554476-f842b718-f124-11e7-88e2-e6c0349bc1f0.png)

**Comment by justinvforvendetta** [comment]
i just received an incoming stealth tx, but i cant confirm where it came from, when discussing the other people ive been testing with. digging deeper.

**Comment by paradoxicalNL** [comment]
Sending to standard non-stealth address did not generate error (popup).
Did not receive coins (yet) however.

I'm off for a quick nap after 48 hours, back later.

**Comment by paradoxicalNL** [comment]
Let me know once you committed a fix and I will thoroughly test!

**Comment by justinvforvendetta** [comment]
i received another stealth tx

**Comment by paradoxicalNL** [comment]
Not from my address imho

Op 4 jan. 2018 6:09 p.m. schreef "sunerok" <notifications@github.com>:

**Comment by fradelo** [comment]
@paradoxicalNL can you give a look again with latest source?

**Comment by jderwish** [comment]
@fradelo  I just compiled latest code, would need someone to send me a test transaction

**Comment by jderwish** [comment]
@justinvforvendetta  are you receiving them on realnetwork or testnet?

**Comment by justinvforvendetta** [comment]
real network.

**Comment by paradoxicalNL** [comment]
Just write your address =]

**Comment by paradoxicalNL** [comment]
I'm seeing same error:

https://github.com/vergecurrency/VERGE/commit/05ca00b3574e66a253c2153ffface4cb75bd2e26
@fradelo @justinvforvendetta @Hamdiovish @jderwish 

CommitTransaction:
CTransaction(hash=6088e3d4e2, nTime=1515100647, ver=1, vin.size=1, vout.size=2, nLockTime=0)
    CTxIn(COutPoint(7f400ab31d, 7), scriptSig=304402205ca238d6c8b523be)
    CTxOut(nValue=1.50, scriptPubKey=OP_DUP OP_HASH160 25b61c8d4b95dffac43fee098d3e48127b9c27ce OP_EQUALVERIFY OP_CHECKSIG)
    CTxOut(error)
AddToWallet 6088e3d4e2  new
WalletUpdateSpent found spent coin 1.80 XVG 7f400ab31d8824a48493f0256960d080ae13d71e16fc92c3f6a83443385be00f
NotifyTransactionChanged 7f400ab31d8824a48493f0256960d080ae13d71e16fc92c3f6a83443385be00f status=1
NotifyTransactionChanged 6088e3d4e2418371bb12abd615f879ebab72263ecf20ce772692f92a77217a8a status=0
NotifyTransactionChanged 7f400ab31d8824a48493f0256960d080ae13d71e16fc92c3f6a83443385be00f status=1
ERROR: CTxMemPool::accept() : nonstandard transaction type
CommitTransaction() : Error: Transaction not validupdateWallet 7f400ab31d8824a48493f0256960d080ae13d71e16fc92c3f6a83443385be00f 1
   inWallet=1 inModel=1 Index=0-1 showTransaction=1 derivedStatus=1
updateWallet 6088e3d4e2418371bb12abd615f879ebab72263ecf20ce772692f92a77217a8a 0
   inWallet=1 inModel=0 Index=0-0 showTransaction=1 derivedStatus=0
received block 5977c684b3cf90ec54ce
updateWallet 7f400ab31d8824a48493f0256960d080ae13d71e16fc92c3f6a83443385be00f 1
   inWallet=1 inModel=1 Index=1-2 showTransaction=1 derivedStatus=1
SetBestChain: new best=5977c684b3cf90ec54ce  height=1774936  trust=1774937  date=04-01-18 21:16:26

**Comment by fradelo** [comment]
@justinvforvendetta @paradoxicalNL this error message is only in one place 
wallet.cpp line 2390

` // Broadcast
        if (!wtxNew.AcceptToMemoryPool())
        {
            // This must not fail. The transaction has already been signed and recorded.
            printf("CommitTransaction() : Error: Transaction not valid");
            return false;
        }
        wtxNew.RelayWalletTransaction(); `

**Comment by jderwish** [comment]
@justinvforvendetta sent a transaction few hours and still didn't receive it. Any comments?

**Comment by fradelo** [comment]
@justinvforvendetta did you check the code that throws the error?
